# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_ModbusDriverViewer.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 424)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.treeView = QtWidgets.QTreeView(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeView.sizePolicy().hasHeightForWidth())
        self.treeView.setSizePolicy(sizePolicy)
        self.treeView.setObjectName("treeView")
        self.tabWidget = QtWidgets.QTabWidget(self.splitter)
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab1)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tableWidget = QtWidgets.QTableWidget(self.tab1)
        self.tableWidget.setRowCount(10)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.verticalLayout_9.addWidget(self.tableWidget)
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btOpen = QtWidgets.QPushButton(self.tab2)
        self.btOpen.setObjectName("btOpen")
        self.verticalLayout_2.addWidget(self.btOpen)
        self.btClose = QtWidgets.QPushButton(self.tab2)
        self.btClose.setObjectName("btClose")
        self.verticalLayout_2.addWidget(self.btClose)
        self.btStop = QtWidgets.QPushButton(self.tab2)
        self.btStop.setObjectName("btStop")
        self.verticalLayout_2.addWidget(self.btStop)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab2)
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lb1_1 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lb1_1.setFont(font)
        self.lb1_1.setFrameShape(QtWidgets.QFrame.Box)
        self.lb1_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lb1_1.setLineWidth(2)
        self.lb1_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lb1_1.setObjectName("lb1_1")
        self.verticalLayout_5.addWidget(self.lb1_1)
        self.lb1_2 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lb1_2.setFont(font)
        self.lb1_2.setFrameShape(QtWidgets.QFrame.Box)
        self.lb1_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lb1_2.setLineWidth(2)
        self.lb1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lb1_2.setObjectName("lb1_2")
        self.verticalLayout_5.addWidget(self.lb1_2)
        self.lb1_3 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lb1_3.setFont(font)
        self.lb1_3.setFrameShape(QtWidgets.QFrame.Box)
        self.lb1_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lb1_3.setLineWidth(2)
        self.lb1_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lb1_3.setObjectName("lb1_3")
        self.verticalLayout_5.addWidget(self.lb1_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab2)
        self.groupBox_3.setFlat(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lb1_d2_1 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lb1_d2_1.setFont(font)
        self.lb1_d2_1.setFrameShape(QtWidgets.QFrame.Box)
        self.lb1_d2_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lb1_d2_1.setLineWidth(2)
        self.lb1_d2_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lb1_d2_1.setObjectName("lb1_d2_1")
        self.verticalLayout_8.addWidget(self.lb1_d2_1)
        self.lb1_d2_2 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lb1_d2_2.setFont(font)
        self.lb1_d2_2.setFrameShape(QtWidgets.QFrame.Box)
        self.lb1_d2_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lb1_d2_2.setLineWidth(2)
        self.lb1_d2_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lb1_d2_2.setObjectName("lb1_d2_2")
        self.verticalLayout_8.addWidget(self.lb1_d2_2)
        self.lb1_d2_3 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lb1_d2_3.setFont(font)
        self.lb1_d2_3.setFrameShape(QtWidgets.QFrame.Box)
        self.lb1_d2_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lb1_d2_3.setLineWidth(2)
        self.lb1_d2_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lb1_d2_3.setObjectName("lb1_d2_3")
        self.verticalLayout_8.addWidget(self.lb1_d2_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem2)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox = QtWidgets.QGroupBox(self.tab2)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lb2_1 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lb2_1.setFont(font)
        self.lb2_1.setFrameShape(QtWidgets.QFrame.Box)
        self.lb2_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lb2_1.setLineWidth(2)
        self.lb2_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lb2_1.setObjectName("lb2_1")
        self.verticalLayout_3.addWidget(self.lb2_1)
        self.lb2_2 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lb2_2.setFont(font)
        self.lb2_2.setFrameShape(QtWidgets.QFrame.Box)
        self.lb2_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lb2_2.setLineWidth(2)
        self.lb2_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lb2_2.setObjectName("lb2_2")
        self.verticalLayout_3.addWidget(self.lb2_2)
        self.lb2_3 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lb2_3.setFont(font)
        self.lb2_3.setFrameShape(QtWidgets.QFrame.Box)
        self.lb2_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lb2_3.setLineWidth(2)
        self.lb2_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lb2_3.setObjectName("lb2_3")
        self.verticalLayout_3.addWidget(self.lb2_3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.verticalLayout_7.addWidget(self.groupBox)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab2)
        self.groupBox_4.setCheckable(False)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lb2_d2_1 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lb2_d2_1.setFont(font)
        self.lb2_d2_1.setFrameShape(QtWidgets.QFrame.Box)
        self.lb2_d2_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lb2_d2_1.setObjectName("lb2_d2_1")
        self.verticalLayout_6.addWidget(self.lb2_d2_1)
        self.lb2_d2_2 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lb2_d2_2.setFont(font)
        self.lb2_d2_2.setFrameShape(QtWidgets.QFrame.Box)
        self.lb2_d2_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lb2_d2_2.setObjectName("lb2_d2_2")
        self.verticalLayout_6.addWidget(self.lb2_d2_2)
        self.lb2_d2_3 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lb2_d2_3.setFont(font)
        self.lb2_d2_3.setFrameShape(QtWidgets.QFrame.Box)
        self.lb2_d2_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lb2_d2_3.setObjectName("lb2_d2_3")
        self.verticalLayout_6.addWidget(self.lb2_d2_3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem4)
        self.verticalLayout_7.addWidget(self.groupBox_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.tabWidget.addTab(self.tab2, "")
        self.tab3 = QtWidgets.QWidget()
        self.tab3.setObjectName("tab3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tab3)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.tableView = QtWidgets.QTableView(self.tab3)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setStretchLastSection(True)
        self.tableView.verticalHeader().setVisible(False)
        self.verticalLayout_10.addWidget(self.tableView)
        self.tabWidget.addTab(self.tab3, "")
        self.verticalLayout_11.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.actionConnect = QtWidgets.QAction(MainWindow)
        self.actionConnect.setObjectName("actionConnect")
        self.actionDevice_Browser = QtWidgets.QAction(MainWindow)
        self.actionDevice_Browser.setCheckable(True)
        self.actionDevice_Browser.setObjectName("actionDevice_Browser")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionConnect_2 = QtWidgets.QAction(MainWindow)
        self.actionConnect_2.setObjectName("actionConnect_2")
        self.actionDisconnect = QtWidgets.QAction(MainWindow)
        self.actionDisconnect.setObjectName("actionDisconnect")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuTools.addAction(self.actionConnect_2)
        self.menuTools.addAction(self.actionDisconnect)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionSettings)
        self.menuHelp.addAction(self.actionAbout)
        self.menuView.addAction(self.actionDevice_Browser)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ModbusViewer"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Address"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Time"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Quality"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Description"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "Registers"))
        self.btOpen.setText(_translate("MainWindow", "OPEN"))
        self.btClose.setText(_translate("MainWindow", "CLOSE"))
        self.btStop.setText(_translate("MainWindow", "STOP"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Modbus1: data1"))
        self.lb1_1.setText(_translate("MainWindow", "TextLabel"))
        self.lb1_2.setText(_translate("MainWindow", "TextLabel"))
        self.lb1_3.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Modbus1: data2"))
        self.lb1_d2_1.setText(_translate("MainWindow", "TextLabel"))
        self.lb1_d2_2.setText(_translate("MainWindow", "TextLabel"))
        self.lb1_d2_3.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox.setTitle(_translate("MainWindow", "Modbus2: data1"))
        self.lb2_1.setText(_translate("MainWindow", "TextLabel"))
        self.lb2_2.setText(_translate("MainWindow", "TextLabel"))
        self.lb2_3.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Modbus2: data2"))
        self.lb2_d2_1.setText(_translate("MainWindow", "TextLabel"))
        self.lb2_d2_2.setText(_translate("MainWindow", "TextLabel"))
        self.lb2_d2_3.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MainWindow", "GUI"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab3), _translate("MainWindow", "View"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.actionConnect.setText(_translate("MainWindow", "Connect .."))
        self.actionDevice_Browser.setText(_translate("MainWindow", "TagList Browser"))
        self.actionDevice_Browser.setShortcut(_translate("MainWindow", "Alt+1"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setToolTip(_translate("MainWindow", "Create new configuration"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOpen.setText(_translate("MainWindow", "Open..."))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As..."))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionConnect_2.setText(_translate("MainWindow", "Connect"))
        self.actionDisconnect.setText(_translate("MainWindow", "Disconnect"))
        self.actionSettings.setText(_translate("MainWindow", "Settings ..."))
